XORSHIFT-ADD(xsadd): xsadd.h File Reference
xsadd.h File Reference
XORSHIFT-ADD: 128-bit internal state pseudorandom number generator.
#include <stdint.h>
#include <inttypes.h>
Data Structures
struct xsadd_t
xsadd internal state vector and parameters
Macros
#define XSADD_FLOAT_MUL (1.0f / 16777216.0f)
#define XSADD_DOUBLE_MUL (1.0 / 9007199254740992.0)
Functions
void xsadd_init (xsadd_t *xsadd, uint32_t seed)
This function initializes the internal state array with a 32-bit unsigned integer seed.
void xsadd_init_by_array (xsadd_t *xsadd, const uint32_t seed[], int size)
This function initializes the internal state array, with an array of 32-bit unsigned integers used as seeds.
static void xsadd_next_state (xsadd_t *xsadd)
This function changes internal state of xsadd.
static uint32_t xsadd_uint32 (xsadd_t *xsadd)
This function outputs 32-bit unsigned integer from internal state.
static float xsadd_float (xsadd_t *xsadd)
This function outputs floating point number from internal state.
static float xsadd_floatOC (xsadd_t *xsadd)
This function outputs floating point number from internal state.
static double xsadd_double (xsadd_t *xsadd)
This function outputs double precision floating point number from internal state.
void xsadd_jump (xsadd_t *xsadd, uint32_t mul_step, const char *base_step)
jump function
void xsadd_jump_by_polynomial (xsadd_t *xsadd, const char *jump_str)
jump using the jump polynomial.
void xsadd_calculate_jump_polynomial (char *jump_str, uint32_t mul_step, const char *base_step)
calculate jump polynomial.
Variables
const char *const xsadd_jump_base_step
Recomended large jump step.
Detailed Description
XORSHIFT-ADD: 128-bit internal state pseudorandom number generator.
Author
Mutsuo Saito (Manieth Corp.)
Makoto Matsumoto (Hiroshima University)
Copyright (c) 2014 Mutsuo Saito, Makoto Matsumoto, Hiroshima University and Manieth Corp. All rights reserved.
Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
Macro Definition Documentation
XSADD_DOUBLE_MUL
#define XSADD_DOUBLE_MUL (1.0 / 9007199254740992.0)
Referenced by xsadd_double().
XSADD_FLOAT_MUL
#define XSADD_FLOAT_MUL (1.0f / 16777216.0f)
Referenced by xsadd_float().
Function Documentation
xsadd_calculate_jump_polynomial()
void xsadd_calculate_jump_polynomial (char * jump_str, uint32_t mul_step, const char * base_step)
calculate jump polynomial.
This function is time consuming. jump_str needs 33 bytes memory.
Parameters
[out] jump_str the result of this calculation.
[in] mul_step jump step is mul_step * base_step.
[in] base_step hexadecimal string of jump base.
Referenced by xsadd_double().
xsadd_double()
static double xsadd_double (xsadd_t * xsadd) inline static
This function outputs double precision floating point number from internal state.
Parameters
[in,out] xsadd xsadd internal state
Returns
floating point number r (0.0 < r <= 1.0)
References xsadd_calculate_jump_polynomial(), XSADD_DOUBLE_MUL, xsadd_jump(), xsadd_jump_base_step, xsadd_jump_by_polynomial(), and xsadd_uint32().
xsadd_float()
static float xsadd_float (xsadd_t * xsadd) inline static
This function outputs floating point number from internal state.
This function is implemented using multiplying by 1 / 2^23. floating point multiplication is faster than using union trick in my Intel CPU.
Parameters
xsadd xsadd internal state
Returns
floating point number r (0.0 <= r < 1.0)
References XSADD_FLOAT_MUL, and xsadd_uint32().
Referenced by xsadd_floatOC().
xsadd_floatOC()
static float xsadd_floatOC (xsadd_t * xsadd) inline static
This function outputs floating point number from internal state.
This function may return 1.0 and never returns 0.0.
Parameters
[in,out] xsadd xsadd internal state
Returns
floating point number r (0.0 < r <= 1.0)
References xsadd_float(), and xsadd_next_state().
xsadd_init()
void xsadd_init (xsadd_t * xsadd, uint32_t seed)
This function initializes the internal state array with a 32-bit unsigned integer seed.
Parameters
[out] xsadd xsadd state vector.
[in] seed a 32-bit unsigned integer used as a seed.
xsadd_init_by_array()
void xsadd_init_by_array (xsadd_t * xsadd, const uint32_t seed[], int size)
This function initializes the internal state array, with an array of 32-bit unsigned integers used as seeds.
Parameters
[out] xsadd xsadd state vector.
[in] seed the array of 32-bit integers, used as a seed.
[in] size the length of seed.
xsadd_jump()
void xsadd_jump (xsadd_t * xsadd, uint32_t mul_step, const char * base_step)
jump function
Parameters
[in,out] xsadd xsadd structure, overwritten by new state after calling this function.
[in] mul_step jump step is mul_step * base_step.
[in] base_step hexadecimal number string less than 2128.
Referenced by xsadd_double().
xsadd_jump_by_polynomial()
void xsadd_jump_by_polynomial (xsadd_t * xsadd, const char * jump_str)
jump using the jump polynomial.
This function is not as time consuming as calculating jump polynomial. This function can use multiple times for the xsadd structure.
Parameters
[in,out] xsadd xsadd structure, overwritten by new state after calling this function.
[in] jump_poly the jump polynomial calculated by xsadd_calculate_jump_polynomial.
Referenced by xsadd_double().
xsadd_next_state()
static void xsadd_next_state (xsadd_t * xsadd) inline static
This function changes internal state of xsadd.
Users should not call this function directly.
Parameters
[in,out] xsadd xsadd internal state
References xsadd_t::state.
Referenced by xsadd_floatOC(), and xsadd_uint32().
xsadd_uint32()
static uint32_t xsadd_uint32 (xsadd_t * xsadd) inline static
This function outputs 32-bit unsigned integer from internal state.
Parameters
[in,out] xsadd xsadd internal state
Returns
32-bit unsigned integer r (0 <= r < 2^32)
References xsadd_t::state, and xsadd_next_state().
Referenced by xsadd_double(), and xsadd_float().
Variable Documentation
xsadd_jump_base_step
const char* const xsadd_jump_base_step
Recomended large jump step.
The value is 3^41.
Referenced by xsadd_double().